### ISSUE TITLE
Desenvolver Diagrama de Casos de Uso

### ISSUE THREAD

**Issue by douglashauschild** [EstacioneFacil/sistema#2]
![usecase_estacionefacil](https://user-images.githubusercontent.com/30798038/29029282-8b3d3ae0-7b5d-11e7-9901-7d46148ebb1b.jpg)

**Comment by douglashauschild** [comment]
Arquivo do diagrama:
[caso_uso.zip](https://github.com/EstacioneFacil/sistema/files/1205084/caso_uso.zip)

**Comment by jonasdiel** [comment]
Acho que é isso mesmo.
