### ISSUE TITLE
Validar cadastro da tabela de preços

### ISSUE THREAD

**Issue by douglashauschild** [EstacioneFacil/sistema#28]
Verificar se já existe um registro de preço cadastrado para tal área, tipo de veículo e vaga.

**Comment by jonasdiel** [comment]
Vamos deixar o campo vaga opcional:

`ALTER TABLE tabela_preco ALTER COLUMN vaga_id DROP NOT NULL;
ALTER TABLE tabela_preco ALTER COLUMN vaga_id DROP DEFAULT;`
