### ISSUE TITLE
Criar Dashboard da área

### ISSUE THREAD

**Issue by jonasdiel** [EstacioneFacil/sistema#31]
Para a área que o usuário autenticou, exibir em forma de botões cada área livre (cor verde) e as ocupadas com o código da placa do veículo (em vermelho). Ao clicar no botão realiza a saida ou entrada.

**Comment by douglashauschild** [comment]
Utilizar a biblioteca MigLayout para auxiliar na montagem dinâmica do dashboard.

Jar + exemplo: [MigLayout.zip](https://github.com/EstacioneFacil/sistema/files/1296301/MigLayout.zip)

![testemig](https://user-images.githubusercontent.com/30798038/30331471-4ad56be0-97ae-11e7-842d-129322e5a242.png)
